# SIN
method: random
metric:
  goal: minimize
  name: val_loss
parameters:
  dim_hidden_treatment:
    distribution: int_uniform
    min: 50
    max: 300
  dim_hidden_covariates:
    distribution: int_uniform
    min: 50
    max: 200
  dim_hidden_propensity:
    distribution: int_uniform
    min: 50
    max: 150
  dim_hidden_como:
    distribution: int_uniform
    min: 200
    max: 300
  dim_output:
    distribution: int_uniform
    min: 50
    max: 250
  num_treatment_layer:
    distribution: int_uniform
    min: 3
    max: 6
  num_covariates_layer:
    distribution: int_uniform
    min: 2
    max: 4
  num_como_layers:
    distribution: int_uniform
    min: 2
    max: 4
  num_propensity_layers:
    distribution: int_uniform
    min: 3
    max: 6
  num_update_steps_global_objective:
    distribution: int_uniform
    min: 10
    max: 20
  patience:
    distribution: categorical
    values:
      - 1
      - 5
  como_patience:
    distribution: categorical
    values:
      - 10
      - 5
  lr:
    distribution: categorical
    values:
      - 0.001
      - 0.0005
  como_dropout:
    distribution: categorical
    values:
      - 0.2
      - 0.
  pro_dropout:
    distribution: categorical
    values:
      - 0.
      - 0.2
program: run_model_training.py
